[versions]
omittable-spring = "2.0.0"
spring-boot = "4.0.2"
springdoc = "3.0.1"


[libraries]
# com.osmerion.omittable-spring-[...] - Omittable - Spring Framework Integration
# https://github.com/Osmerion/omittable-spring
omittable-spring-webflux = { module = "com.osmerion.omittable:omittable-spring-webflux", version.ref = "omittable-spring" }
omittable-spring-webmvc = { module = "com.osmerion.omittable:omittable-spring-webmvc", version.ref = "omittable-spring" }

# com.osmerion.omittable-spring-[...] - Omittable - Swagger Core Integration
# https://github.com/Osmerion/omittable-swagger-core
omittable-swagger-core = { module = "com.osmerion.omittable:omittable-swagger-core", version = "0.7.0" }

# org.springframework.boot - Spring Boot
# https://github.com/spring-projects/spring-boot
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure", version.ref = "spring-boot" }
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-jackson2 = { module = "org.springframework.boot:spring-boot-jackson2", version.ref = "spring-boot" }
spring-boot-resttestclient = { module = "org.springframework.boot:spring-boot-resttestclient", version.ref = "spring-boot" }
spring-boot-starter-restclient-test = { module = "org.springframework.boot:spring-boot-starter-restclient-test", version.ref = "spring-boot" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test", version.ref = "spring-boot" }
spring-boot-starter-webflux-test = { module = "org.springframework.boot:spring-boot-starter-webflux-test", version.ref = "spring-boot" }

# org.springdoc - springdoc
# https://github.com/springdoc/springdoc-openapi
springdoc-openapi-starter-common = { module = "org.springdoc:springdoc-openapi-starter-common", version.ref = "springdoc" }
springdoc-openapi-starter-webflux-ui = { module = "org.springdoc:springdoc-openapi-starter-webflux-ui", version.ref = "springdoc" }
springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
